name: codenerf
channels:
  - pytorch
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pip:
      - opencv-python
      - tensorboard
      - imageio
      - imageio-ffmpeg
      - lpips
      - nuscenes-devkit
      - cityscapesScripts
  - scipy
  - numpy
  - matplotlib
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.3
  - scikit-image
  - tqdm